# Site settings
title: My Awesome Blog
description: A blog about awesome things.
baseurl: "" # Leave blank for root or specify subdirectory
url: "https://Ethan''s.com"

# Author information
author:
  name: Jane Doe
  email: jane.doe@example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pagination
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

# Social links
social:
  twitter: janedoe
  github: janedoe

